version: '3.7'
services:
  postgres:
   image: postgres:14.1-bullseye
   container_name: postgres
   environment:
     POSTGRES_USER: tinypod
     POSTGRES_PASSWORD: secret
     POSTGRES_DB: tinypod
   ports:
     - "5432:5432"

  mongodb:
    image: mongo:5.0.5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: tinypod
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
    - "27017:27017"
