name: argo handson
on:
  push:
    branches:
    - main
    - actions

jobs:
  deploy:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
    runs-on: ubuntu-20.04
    env:
      AWS_REGION: ap-northeast-1
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_NAME }}
      run: |
        docker image build --tag "${ECR_REGISTRY}/${ECR_REPOSITORY}:sha-${GITHUB_SHA}" .
        docker image push ${ECR_REGISTRY}/${ECR_REPOSITORY}:sha-${GITHUB_SHA}

    - name: Checkout kubernetes manifest repository
      uses: actions/checkout@v2
      with:
        repository: ymgyt/argocd-handson-gitops
        token: ${{ secrets.GH_PAT }}
        path: argocd-handson-gitops
        ref: main

    - name: Setup kubectl
      id: kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: "v1.22.4"

    - name: Patch new image
      env:
        DEPLOYMENT: argocd-handson-gitops/tinypod/base/deployment.yaml
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_NAME }}
      run: |
        kubectl patch \
          --local \
          --filename ${DEPLOYMENT} \
          --patch '{"spec":{"template":{"spec":{"containers":[{"name": "tinypod","image": '\"${ECR_REGISTRY}/${ECR_REPOSITORY}:sha-${GITHUB_SHA}\"'}]}}}}' \
          --output yaml > ${DEPLOYMENT}.tmp && mv ${DEPLOYMENT}.tmp ${DEPLOYMENT} 

    - name: Git Status
      run: |
        cd argocd-handson-gitops
        git status

    - name: Push git commit to kubernetes manifest repository
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_NAME }}
      run: |
        cd argocd-handson-gitops
        git add . -m "update deployment image to ${ECR_REGISTRY}/${ECR_REPOSITORY}:sha-${GITHUB_SHA}"
        git push origin main




